dist: trusty
language: rust
rust:
- stable
env:
  global:
  - CRATE_NAME=hclrs
  - secure: qHgqv+bB+0uBgTkh1sQljde6Gi75tQa78L+dNExRdxYd0MhzHQSUkt48lwtlekl7rgznjabHFZBVXo1cMwpxTz/45DwT3TVZ1lneXi3PH8SSrN/OxfJSLilyB4GCDEweNJCQNZ5GwKe3hvhk92GugKEyKUcSCqP6BI+U+2gJCNUVq8qTAkQf8p+SoFBS0yeefpzYRh+Hu1EhUEBHcAKgWu1j7LcnU2K4JN8qNCL3S80YTeKKXad14ZBLuexevzwikYvZSrPuwbQH1KKl0YzWEhMBD/12lhgnZWDO6R0AuHr/4Xxt1vSQvj+sGsi/tAEcLYFFuh9GKqFbJITU2gYCrsFAHQj+JxmoTUSZWfILrt7dolPd/giU4q92rBUBweWFlyIgJ8qf+Z4zOGKvBy3dVkSJcVkYZ+dny0iuDOU7k+zoH15hXLUMhpvTcJaEkX0Izbs1RhdFqB2v13QHj63ZQ/RaTBYDWLA5O/BiG6AP01KVC2uFNlmE3rH1YDvJ5FqAGvt4BcsmWsP6TfPokexGwFeQLGl+MgYR3xuiQxTV+9ITla3MhmvimJZMlwr7Mf3AQQyKSZf82sfbiTBJNQjtDnyAHEShMoqz6D/RnL+e6ykxsILa+FFTZ7G+j0SC7yBMeK4sVCk+7oai0K3LRC2wd1doEs4pzw3XbBmDXIpDCGU=
matrix:
  include:
  - env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages:
        - gcc-multilib
  - env: TARGET=i686-unknown-linux-musl
    addons:
      apt:
        packages:
        - gcc-multilib
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
before_install: set -e
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: BFDjEH77LLw+svTYcwaVpbwtm73WRmg/MgvqysBtogfOkyfZ+3+WRIMuO4/ima9zvAfXunAgp7l77RXe9ojyfj8OsGvyVX1PMT777hFg61p0ed1MVBM5qW4j6cotwIU+C9yFRs5DHVSk7QTWIlApDVkw+un+/tS39TuaY0EfUDkfQa3V3BnoxYQl/gWrihRGPLb//AnMHyJ8nlZFNIqelJdMGNji3I1xXXilELya6RHgIVIaQqnZPfricNukI7IO3UQo2KxDIOQzYVskFPWxh8k45QqR4SaFoNKgZV+UGDWYTsIel6oYySgh2Aj+AkT8fpWSlKYqYO6CfNFboTREA5UR5DFKRqQX4htzw7DIT3kJqc5OkwV52mdqsPyRIXh70kZXxxbB9oRT3rPh96vw5x6K7R7bqIV4uHUKsmT8qrdqVcbJCWchDBI5TAVGI0cNN2HX/xWlUrYtpOUPa2xKQTg9SS3iEDGj4wB8akywxTB4F9GoGwMGud0VfCHOy3C+sQ0+oeES9ALN2qvTPcQ2oiaySZytqWjBQsUWMQXO6M4y10NeZ5LeVl6GW60dP4yhgTu3TA1lM8/9lDVYbJA6bUCei84H+fPUnNFTBk9h0n3841+MzKG9l9mu7ma8T2Iyz2kJNAlpUoEDjv+zXoznDU66NPL/uFBC6O2TwHFUofQ=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
