[package]
name = "hclrs"
version = "0.1.0"
authors = ["Charles Reiss <cr4bd@virginia.edu>"]

build = "build.rs" # LARLRPOP preprocessing

[features]
default = ["strict-boolean-ops"]
strict-boolean-ops = []
strict-wire-widths-binary = []

[profile.release]
lto = true

# For tokenization
[dependencies.regex]
version = "0.2.1"

# Parser runtime library
[dependencies.lalrpop-util]
version = "0.13.0"

# Parser library
[build-dependencies.lalrpop]
version = "0.13.0"

# For u128
[dependencies.extprim]
version = "1.2.2"

[dependencies.num-traits]
version = "0.1.39"

[dependencies.log]
version = "0.3.8"

[dependencies.env_logger]
version = "0.4.3"

[dependencies.getopts]
version = "0.2"
